version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
sphinx:
  configuration: docs/source/conf.py
formats: all
python:
  install:
    - requirements: docs/source/requirements.txt
    - path: .
